### PR TITLE
Fixed Imports to make the code more readable

### PR DESCRIPTION
**Pull request by bayush-9**
#9  The imports are managed properly now. Comments are added to make code more readable.

### CODE REVIEW

**Review by Kushalrock — CHANGES_REQUESTED** [review]
There are some obvious changes that are required
1. In the theme.dart file package:flutter is used. Above that, there is no comment saying // Flutter Imports. I have not seen other files. But if there are other files with this thing not mentioned please rectify it.
2.  In main.dart package:routinger/config/theme.dart is used which would be a relative import. That is it should be './config/theme.dart'. In several other places package:routinger is used. Also, in some places package:routinger is inside the third party packages. There should be no package:routinger because those can be described by relative imports. An example would be
`package:routinger/config/theme.dart` will be `./config/theme.dart` inside the comment `// Config Imports`.
3. package:provider is not a provider import because the first two words are not package:routinger or package:futter or any relative import. So, it should come under third party packages.
4. Also typos like // Third Pstry Packages in add_task.dart file.

**Comment by Kushalrock** [comment]
@bayush-9  Please take a look at the changes requested.

**Comment by bayush-9** [comment]
Okay. Working on it.

**Comment by Kushalrock** [comment]
@bayush-9  Some tiny changes are required. In the issue I asked you to follow a definite order as per the local folders.
That is 
// Dart Packages 
// Flutter Packages
// Third party Packages
// config imports
// constant imports
// helper imports
// provider imports

and so on.. that is the imports should be like the folder structure. The folder which comes first their imports should be above the folder which comes below them.

**Review by Kushalrock — APPROVED** [review]
Approving the changes. All requested changes were made. And the app's functionality doesn't break.

**Pull request merged**
